planner_joint_impedance_hi:
  type: "itia/control/TopicHwIfaceNodelet"
  
  joint_names: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic  : "/iiwa/joint_states"
  command_joint_state_topic   : "/joint_impedance_pos_target"
  sampling_period             : 0.005
  diagnostic_period           : 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/cancel"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/feedback"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/goal"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/result"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/status"
  remap_target_args: 
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/cancel"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/feedback"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/goal"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/result"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/status"
  
  thor:
    type: "thor/PrefilterPosController"
    controlled_joint: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    spline_order: 1
    
  joint_teleop_ctrl:
    type: "itia/control/JointTeleopController"
    controlled_joint: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    


