control_configurations:
  - name: "watch"
    components: 
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"

  - name: "thor_prefilter_planner"
    components: 
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "thor_prefilter_planner"
        
  - name: "joint_impedance"
    components:
      - description: ""
        hardware_interface: "planner_joint_impedance_hi"
        controller        : "thor"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "joint_impedance_ctrl"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"
    
  - name: "cartesian_impedance"
    components:
      - description: ""
        hardware_interface: "planner_joint_impedance_hi"
        controller        : "thor"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "cartesian_impedance_ctrl"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"
    
  - name: "joint_teleop"
    components:
      - description: ""
        hardware_interface: "iiwa"
        controller        : "joint_teleop_ctrl"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"

  - name: "cart_teleop"
    components:
      - description: ""
        hardware_interface: "iiwa"
        controller        : "cart_teleop_ctrl"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"
        
  - name: "touch"
    components:
      - description: ""
        hardware_interface: "twist_hi"
        controller        : "touch_control"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "cart_teleop_ctrl"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"


  - name: "teleop_impedance"
    components:
      - description: ""
        hardware_interface: "planner_joint_impedance_hi"
        controller        : "joint_teleop_ctrl"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "joint_impedance_ctrl"
      - description: ""
        hardware_interface: "iiwa"
        controller        : "js_pub"
        
        
planner_joint_impedance_hi:
  type: "itia/control/TopicHwIfaceNodelet"
  
  joint_names: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic  : "/iiwa/joint_states"
  command_joint_state_topic   : "/joint_impedance_pos_target"
  sampling_period             : 0.005
  diagnostic_period           : 0.1
  feedback_joint_state_timeout: 20

  remap_source_args:
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/cancel"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/feedback"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/goal"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/result"
  - "/planner_joint_impedance_hi/thor/follow_joint_trajectory/status"
  - "/twist_hi/touch_control/robot_description"
  remap_target_args: 
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/cancel"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/feedback"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/goal"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/result"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/status"
  - "/robot_description"
  
  thor:
    type: "thor/PrefilterPosController"
    controlled_joint: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    spline_order: 1
    
  joint_teleop_ctrl:
    type: "itia/control/JointTeleopController"
    controlled_joints: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    
    
twist_hi:
  type: "itia/control/TopicHwIfaceNodelet"
  
  joint_names: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
  allowed_controller_types:
  - "controller_type1"
  feedback_joint_state_topic  : "/iiwa/joint_states"
  command_joint_state_topic   : "/iiwa/touch_control/target_cart_teleop"
  sampling_period             : 0.005
  diagnostic_period           : 0.1
  feedback_joint_state_timeout: 20
  
  touch_control:
    type              : "itia/control/SimpleTouchController"
    controlled_joints : [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    base_link         : "iiwa_link_0"
    tool_link         : "iiwa_link_ee"
    sensor_frame      : "iiwa_link_ee"
    wrench_topic_name : "/wrench_tool"
    target_wrench     : [0,0,-10,0,0,0]
    wrench_toll       : [1,1,1,1,1,1]



iiwa:
  type: "itia/control/IiwaHwIfaceNodelet"
  
  iiwa_control_mode: "fri"
  fri:
    filter/wrench/saturation          : [ 900., 900., 900., 900., 900., 900. ]
    filter/wrench/deadband            : [  1.5,  1.5,  1.5, 0.15, 0.15, 0.15 ]
    filter/wrench/cutoff_frequency_hz : 20
    filter/twist/saturation           : [   200.,   200.,   200.,   200.,   200.,   200. ]
    filter/twist/deadband             : [ 0.0001, 0.0001, 0.0001, 0.0001, 0.0001, 0.0001 ]
    filter/twist/cutoff_frequency_hz  : 20
    port                              : 30200
    hostname                          : 172.31.1.147
    timeout_ms                        : 5000
    cycle_time_s                      : 0.005
    robot_description_param           : "/robot_description"
    base_link                         : "iiwa_link_0"
    tool_link                         : "iiwa_link_ee"
    state_publisher_freq_hz           : 50
    max_joint_velocity_allowed        : [  1.5,  1.5,  1.5, 1.5, 1.5, 1.5, 1.5 ]

  defaultMinimumTrjectoryExecution: 10.e-3
  publishJointStates              : true
  defaultRelativeJointSpeed       : 1.0
  defaultRelativeJointAcceleration: 1.0

  joint_names             : [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
  allowed_controller_types: 
  - "controller_type1"  
  
  sampling_period: 0.005
  diagnostic_period: 0.1
  feedback_joint_state_timeout: 20
  maximum_missing_messages: 1000

  remap_source_args:
  - "/iiwa/thor_prefilter_planner/follow_joint_trajectory/cancel"
  - "/iiwa/thor_prefilter_planner/follow_joint_trajectory/feedback"
  - "/iiwa/thor_prefilter_planner/follow_joint_trajectory/goal"
  - "/iiwa/thor_prefilter_planner/follow_joint_trajectory/result"
  - "/iiwa/thor_prefilter_planner/follow_joint_trajectory/status"
  - "/iiwa/cart_teleop_ctrl/target_cart_teleop"
  remap_target_args: 
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/cancel"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/feedback"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/goal"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/result"
  - "/iiwa/thor_prefilter_controller/follow_joint_trajectory/status"
  - "/iiwa/touch_control/target_cart_twist"

  thor_prefilter_planner:
    type: "thor/PrefilterPosController"
    controlled_joint: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    spline_order: 1

  js_pub:
    type: "joint_state_controller/JointStateController"
    publish_rate: 200
    
  joint_impedance_ctrl:
    type: "itia/control/JointImpedanceController"
    controlled_joint      : [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    inertia               : [10,10,10,10,10,10,10]
    stiffness             : [100,100,100,100,100,100,100]
    #  2 * c * sqrt(m*k)
    damping               : [30,30,30,30,30,30,30]
    torque_deadband       : [2,2,2,2,2,2,2]
    joint_target_topic    : "/joint_impedance_pos_target"
    use_wrench            : true
    external_wrench_topic : "/wrench_tool"
    base_frame            : "iiwa_link_0"
    tool_frame            : "iiwa_link_ee"
    sensor_frame          : "iiwa_link_ee"
    
  joint_teleop_ctrl:
    type             : "itia/control/JointTeleopController"
    controlled_joints: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    
  cart_teleop_ctrl:
    type            : "itia/control/CartTeleopController"
    controlled_joints: [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    base_link       : "iiwa_link_0"
    tool_link       : "iiwa_link_ee"
    
  cartesian_impedance_ctrl:
      # REQUIRED:
    type                  : "itia/control/CartImpedanceController"
    inertia               : [ 10, 10, 10,  10, 10, 10]    
    stiffness             : [500,500,500, 50,50,50]   
    damping               : [120,120,120, 120,120,120]   
    joint_target_topic    : "/joint_impedance_pos_target"
    base_frame            : "iiwa_link_0"
    tool_frame            : "iiwa_link_ee"
    sensor_frame          : "iiwa_link_ee"
    
    # OPTIONAL: 
    base_is_reference     : false
    wrench_deadband       : [1,1,1,1,1,1] 
    external_wrench_topic : "/wrench_tool"
    controlled_joint      : [iiwa_joint_1,iiwa_joint_2,iiwa_joint_3,iiwa_joint_4,iiwa_joint_5,iiwa_joint_6,iiwa_joint_7]
    damping_ratio         : [2,2,2,1.2,1.2,1.2]               

    
    
    
