path_tolerance: 0.01
goal_tolerance: 0.001

  
home:
  positions:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  velocities:
  - [0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  time_from_start:
  - 8.0
  joint_names:
  - iiwa_joint_1
  - iiwa_joint_2
  - iiwa_joint_3
  - iiwa_joint_4
  - iiwa_joint_5
  - iiwa_joint_6
  - iiwa_joint_7


P1:
  positions:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  - [2.0, 0.0, -0.5, 1.507, 0.0, 2.0, 2.0]
  - [-2.0, 0.0, 0.5, -1.507, 0.0, 2.0, 2.0]
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  velocities:
  - [1.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  - [1.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  - [1.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  - [1.5, 0.5, 0.5, 0.5, 0.5, 0.5]
  time_from_start:
  - 0.0
  - 1.0
  - 2.0
  - 3.0
  joint_names:
  - iiwa_joint_1
  - iiwa_joint_2
  - iiwa_joint_3
  - iiwa_joint_4
  - iiwa_joint_5
  - iiwa_joint_6
  - iiwa_joint_7

